import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:roadwatch/services/auth_service.dart';

class PdfUtils {
  static Future<void> generateReportPdf(
    List<Map<String, dynamic>> selectedReports, {
    bool isAdmin = false,
  }) async {
    final user = AuthService.currentUser;
    final role = await AuthService.getRole();

    final pdf = pw.Document();

    for (final report in selectedReports) {
      print(report);
    }

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                "RoadWatch Report Summary",
                style: pw.TextStyle(
                  fontSize: 20,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.blue,
                ),
              ),
              pw.SizedBox(height: 5),
              if (user != null && !isAdmin) ...[
                pw.Text(
                    "Name: ${user.email.split('@').first}"), // Assuming name from email
                pw.Text("Email: ${user.email}"),
              ],
              if (isAdmin || role == 'admin') ...[
                pw.Text("Generated by Admin"),
              ],
              pw.SizedBox(height: 10),
              pw.Text(
                "Generated on: ${DateTime.now().toString().split(' ').first}",
                style: pw.TextStyle(fontSize: 12, color: PdfColors.grey),
              ),
              pw.SizedBox(height: 20),
              pw.Table.fromTextArray(
                headers: [
                  "Date",
                  "Time",
                  "Place",
                  "Status",
                  "Severity",
                  "Upvotes"
                ],
                data: selectedReports.map((report) {
                  return [
                    report['date'] ?? "N/A",
                    report['time'] ?? "N/A",
                    report['location'] ?? "N/A",
                    report['status'] ?? "N/A",
                    report['severity'] ?? "N/A",
                    report['upvotes']?.toString() ?? "0",
                  ];
                }).toList(),
                headerStyle: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                ),
                headerDecoration: pw.BoxDecoration(
                  color: PdfColors.grey300,
                ),
                cellStyle: pw.TextStyle(fontSize: 10),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }
}
